### ISSUE TITLE
Showcase All of the Player's Vault Ranks

### ISSUE THREAD

**Issue by Twotters** [PlaceholderAPI/Vault-Expansion#11]
On my network, there are a few places that I would like to display all of the user's ranks.
This is helpful for players with both a Staff rank & Donator rank, and for donators with two separate ranks (IE VIP/Diamond).

The %vault_rank% placeholder only displays the player's most recent rank.
A placeholder listing all of the player's ranks would be gorgeous. 

%vault_ranks% = `VIP, Diamond`

**Comment by aBooDyy** [comment]
Hello,
Thanks for your suggestion, I've just added `%vault_ranks%` and `%vault_ranks_capital%` to my fork.
You can download it from [here](https://aboodyy.net/expansions/PAPI-Expansion-Vault.jar). I haven't tested it myself, but it should work fine. Approval from you that its working fine would be great.

To install the new version:
- Go to `/plugins/PlaceholderAPI/expansions/` folder.
- Delete the old jar of Vault expansion.
- Add the new jar (you downloaded from the link above) there.
- Reload PlaceholderAPI (`/papi reload`).

**Comment by extendedclip** [comment]
Lmk if it works and push a pr to the official repo if so

**Comment by Andre601** [comment]
He already did. See #10

**Comment by Twotters** [comment]
Endless thanks! :^)
Great work homie, appreciate this.

**Comment by Twotters** [comment]
* Works exactly as you intended

**Comment by Twotters** [comment]
* Works as intended! :)

**Comment by aBooDyy** [comment]
The new changes are live on the cloud now!
Let us know if there's something wrong.
