### ISSUE TITLE
PlaceholderAPI constantly throws errors when using latest Vault expansion

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/Vault-Expansion#12]
When you download the latest Vault-Expansion (v1.6.0 as of this issue) does PlaceholderAPI throw the following errors every ~5 seconds once you reloaded the plugin or restarted the Server:
https://paste.helpch.at/tomotopita.md

This error won't appear when you downgrade to 1.5.2

**Comment by Andre601** [comment]
I checked myself and it seems that the for-loop in the BalTopTask returns or receives null?

https://github.com/PlaceholderAPI/Vault-Expansion/blob/a4514ea5921c8729dfacca716ebc6eef4d384253/src/main/java/com/extendedclip/papi/expansion/vault/BalTopTask.java#L44

Can someone please look at this? It's really annoying to have.

**Comment by aBooDyy** [comment]
Hello there,
I've just tried it on the latest version of paper, and in the same build from the error you sent and it's working fine.
According to paper staff from Clip's conversation with them, that it's due to a broken server environment.
Can you try it elsewhere? In a hosted server maybe if you're getting that error in localhost.

**Comment by Kqliber** [comment]
This error has crept upon in helpchat discord server.
someone on 1.8 server version (papi v2.10.6) had the following error.
https://hasteb.in/fayuwibu.cs

if this issue could be looked into again thatll be great

**Comment by aBooDyy** [comment]
Hello @Kqliber,

Thanks for bringing it here,
It's a different error from the one Andre reported. And as I can see, it seems to be an issue with Essentials and not PAPI's Vault Expansion.
I suggest you report this to Essentials.

Kind regards,
aBooDyy
