### ISSUE TITLE
Has Permission placeholder

### ISSUE THREAD

**Issue by Tanguygab** [PlaceholderAPI/Vault-Expansion#14]
Hey 👋 
I wanted to know if you could add a placeholder like `%vault_has_permission_<permission here>%` that supports offline players.
I know there's a placeholder in the Player and LuckPerms expansions, but none support offline players ;-;

Could it be possible to add it ? Thanks =)

**Comment by Vikbor5342** [comment]
Im prety sure luckperms support offline players.

**Comment by Tanguygab** [comment]
I tried a while ago, but it didn't, I'll try again later when I can, but I don't remember it working

**Comment by BlitzOffline** [comment]
You should understand that there's a reason it doesn't work for offline players. especially for offline ones. Its wouldn't be very good to access the luckperms database every time it is parsed.

**Comment by Tanguygab** [comment]
close it, I don't have a server anymore and yeah it wouldn't really be efficient
