### ISSUE TITLE
%vault_prefix% just return %vault_prefix%

### ISSUE THREAD

**Issue by Rothes** [PlaceholderAPI/Vault-Expansion#15]
%vault_prefix% just return %vault_prefix%
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Rothes** [comment]
sorry.it is the problem of the other plugin

**Comment by Andre601** [comment]
Please don't edit/remove your issue like that.
It is frustrating and could cause issues if people randomly find it and wonder what happened here.
