### ISSUE TITLE
Wasted CPU ressources

### ISSUE THREAD

**Issue by TNTUP** [PlaceholderAPI/Vault-Expansion#16]
Hey, I decided to take a hunt on CPU usage and I noticed since several days, from an empty server to 10 players (no heavy activity involved/expected) using nearly 8-11% (~60-80% on a single core, on a 4C/8T system) by using the expansion Vault.

The server has like 10K of unique players and I diagnosed by deleting (I did a backup FIRST) all playerdata and I noticed CPU usage going down to 0-2% idling and under 10 players ~5-8% (assuming no heavy activity).

I removed the Expansion-Vault then restarted the server and monitoring for 5 minutes. Below 3% idle usage. With the Expansion enabled, over 8-10% if you have a lot (I mean a lot, maybe over 100-200 unique players) you'll notice small CPU spikes but if you have like 1000-10000 of unique players, it will mean a lot. 

OS: WS2019 x64
Java: java version "1.8.0_251"`
MC Version: 1.16.3 (PaperSpigot Build 195)
PAPI Version: 2.10.9
Expansion-Vault Version: 1.6.0

My english sucks so bad sorry if there's inconsistencies, bad grammar :(

**Comment by darbyjack** [comment]
Thanks for bringing this up. I noticed that not everyone uses the baltop placeholders, so as a start-fix, I've pushed an update to the eCloud that has it disabled by default. If you aren't using the baltop placeholders in it, head to the PlaceholderAPI config and disable the `baltop` section.
