### ISSUE TITLE
Placeholder 'prefix_color' doesn't return hex codes

### ISSUE THREAD

**Issue by tjalp** [PlaceholderAPI/Vault-Expansion#17]
I've already created an issue [here](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/489) and it was said that this was a PlaceholderAPI issue, not the expansion's. However, it seems to me that this is also this expansion's issue as seen in this method:
https://github.com/PlaceholderAPI/Vault-Expansion/blob/ed65d8ee9befdf021083dfeaaa46bbde6299dcab/src/main/java/com/extendedclip/papi/expansion/vault/VaultPermsHook.java#L230

Seems to me that instead of returning the last color code, you can just return a string of all color codes in chronological order.

Just wanted to notify you of this since I do actually use this placeholder very often.

**Comment by apatuka** [comment]
Having the same problem, did you find a solution?

**Comment by tjalp** [comment]
> Having the same problem, did you find a solution?

Pretty sure I ended up just doing parsing it myself instead of using the placeholder
