### ISSUE TITLE
XConomy - PAPI exception while executing task 

### ISSUE THREAD

**Issue by TKwSni** [PlaceholderAPI/Vault-Expansion#20]
I'm getting this randomly while using 

[XConomy](https://www.spigotmc.org/resources/xconomy.75669/) but very often sometimes.
https://paste.gg/p/anonymous/13f4dde4184944d58f66d3dc98e0cbe3/files/6b4179e3e6794a17814793643909924f/raw

**Comment by Andre601** [comment]
Error comes from `at me.yic.xconomy.depend.Vault.getBalance(Vault.java:135)` so it's caused in xconomy on Line 135 in Vault.java
https://github.com/YiC200333/XConomy/blob/master/src/main/java/me/yic/xconomy/depend/Vault.java#L135

The method there probably returns `null` which causes this issue. Can't guarantee it to be the cause but you should also ask on the xconomy github about this.

**Comment by TKwSni** [comment]
Yes but, I changed some settings on papi (it was a warning about vault balance) and it was fixed.
