### ISSUE TITLE
PlaceholderAPI and Vault Issue

### ISSUE THREAD

**Issue by Dimitryyyy** [PlaceholderAPI/Vault-Expansion#21]
Hello! I have a server (Spigot 1.8.8), where i am the owner. And i'm using vault and Placeholders... And then, if i use the vault placeholders on the scoreboard, doesnt work. So i'm in Owner group, but in the scoreboard, i'm default. I send a photo. (Sorry for the "Rangod", this is hungarian it means: Your Rank)  [https://i.imgur.com/KVuP3TA.png](url)

**Comment by Andre601** [comment]
Your URL isn't working. Did you override it like this: `[https://i.imgur.com/KVuP3TA.png]()`?

Because that makes it impossible to click and view.

**Comment by Starmism** [comment]
PAPI does not parse scoreboard placeholders. You'd need a scoreboard plugin that works with PAPI to use that.
