### ISSUE TITLE
Formatting money - Vault

### ISSUE THREAD

**Issue by ItzOrazioh** [PlaceholderAPI/Vault-Expansion#23]
hi, I would like to make a request that I really need, I saw that the maximum formatting of the vault expansion, supports a maximum of 1000Q, I would like to ask if it is possible to enlarge it and make it reach 1000Dc, Example: (1k - 1m - 1b - 1t - 1q - 1qt - 1sx - 1sp - 1oc - 1no - 1dc)

**Comment by Phoenix616** [comment]
Would be a lot better if Vault's inbuilt balance formatting method was used... then economy plugins could define that on their own how they want to format balances globally.
