### ISSUE TITLE
New placeholder for money

### ISSUE THREAD

**Issue by siulung201314** [PlaceholderAPI/Vault-Expansion#25]
I would like to suggest some placeholders.
%vault_eco_balance_1dp%
%vault_eco_balance_2dp%
%vault_eco_balance_3dp%

For example, %vault_eco_balance_2dp%
When the player has 123456.45678, %vault_eco_balance_2dp% shows 123456.45 without rounding up.

**Comment by Tanguygab** [comment]
you can use the Math expansion to round placeholders with %math_<rounding>_{placeholder}%, for example: %math_0_{vault_eco_balance}%
