### ISSUE TITLE
[BUGS] %vault_prefix_color%

### ISSUE THREAD

**Issue by Thin-Troll** [PlaceholderAPI/Vault-Expansion#26]
When setting a custom prefix to a player,% vault_prefix_color% takes the color from the group, not from the player's data.
LuckPerms

**Comment by Andre601** [comment]
That's because the prefix you want to use is `%vault_user_prefix_color%`
`%vault_prefix_color%` returns the color of the last (primary) group the user has

**Comment by Thin-Troll** [comment]
solved my question. thanks!
