### ISSUE TITLE
Top Balance Placeholders Don't Work

### ISSUE THREAD

**Issue by Reese14** [PlaceholderAPI/Vault-Expansion#29]
The placeholders that involve top balances (such as %vault_eco_top_balance_commas_#% and %vault_eco_top_player_#%) are not showing anything. It outputs 0.0 and a blank space for the player placeholder.

Can show proof if needed

Server Version: Paper-788 (MC: 1.16.5)
Vault Version: Vault v1.7.3-b131
EssentialsX version: 2.18.2.0

**Comment by Geolykt** [comment]
Related vault issues: https://github.com/MilkBowl/Vault/issues/861, https://github.com/MilkBowl/Vault/issues/851

**Comment by BlitzOffline** [comment]
I am not sure if you guys are aware but the placeholders are being removed from the expansion and are being moved in the essentials expansion. There is currently a development build in our discord server: https://discord.gg/helpchat in the #placeholder-api channel.

If you still want this to work in the vault expansion I believe you have to download the version 1.5.2 of the expansion and enable it in the config.
