### ISSUE TITLE
Suggestion: New Placeholder

### ISSUE THREAD

**Issue by Coniculls13** [PlaceholderAPI/Vault-Expansion#3]
I wish to suggest a new vault placeholder.
Currently available if %vault_rank% but you are not able to specify which rank it should show if the user has multiple. 
What if there was a variable option on the end of it to specify which rank ladder it should prioritise?
Like %vault_rank_ladderName%

**Comment by Mishyy** [comment]
I don't believe this functionality is native to Vault itself, rather specific permission/group management plugins.  Such a feature would most likely need to be implemented within their specific placeholder expansions, if they have any.

I believe LuckPerms has a PApi expansion [here](https://github.com/lucko/LuckPerms/wiki/Placeholders).
