### ISSUE TITLE
last_color returns the entire prefix/suffix

### ISSUE THREAD

**Issue by BlitzOffline** [PlaceholderAPI/Vault-Expansion#31]
In the getLastColor() method, if the color is at the start of the prefix or suffix and there is no color after, it returns the entire prefix or suffix. I am not sure if this is how it is meant to work. leaving it here for the people that work on the expansion.

https://github.com/PlaceholderAPI/Vault-Expansion/blob/8a13110ccdd31ddd7b002e2ca13169244cb87375/src/main/java/com/extendedclip/papi/expansion/vault/VaultPermsHook.java#L222

**Comment by iGabyTM** [comment]
The placeholder was removed.
