### ISSUE TITLE
Placeholders not working in name and skins not working as well

### ISSUE THREAD

**Issue by Florens11** [PlaceholderAPI/Vault-Expansion#33]
![image](https://user-images.githubusercontent.com/52450422/151705948-61a21482-f01c-4f4a-9a82-c4da1b9924fe.png)

I want the NPC to have the name of the top island level leader.

As you can see its not working.

Citizens version; Citizens 2.0.29-SNAPSHOT (Build 2457)

![image](https://user-images.githubusercontent.com/52450422/151705960-f199c023-51cc-406b-a8d8-d145d30c8134.png)

**Comment by Andre601** [comment]
How is this an issue with the **Vault expansion**?

You clearly use a different placeholder and/or plugin.

**Comment by BlitzOffline** [comment]
Closing this as there has been no update from the OP and the original post clearly has nothing to do with the vault expansion.
