### ISSUE TITLE
PermissionEx Bug with %vault_prefix%

### ISSUE THREAD

**Issue by Lastphysics** [PlaceholderAPI/Vault-Expansion#9]
When im using the vault %vault_prefix% for the rankup plugin, nothing shows up sadly :/. Only the %vault_rankup% works

The permission plugin is Permissionex, could you make an update for it ? Or just has it something to do with vault directly ?

**Comment by aBo0oDyy** [comment]
If `%vault_prefix%` returns nothing, then you don't have a prefix to return.
`%vault_rankup%` isn't a placeholder ? are you sure you're using the latest version of Vault expansion?

Please open the issue in the correct place next time.

**Comment by Andre601** [comment]
Also youshouldswitch to LuckPerms.
It is updated, maintained and the dev of PEX recommends to switch to it.

**Comment by aBooDyy** [comment]
Hello @Lastphysics,
Is this still not working fine for you?

The issue will be closed in a few days if we haven't heard from you.

**Comment by Lastphysics** [comment]
Sorry, dont have time to look into it. Not sure if it works or not

**Comment by aBooDyy** [comment]
Ok then, I'll close this issue because most likely it will work. Feel free to open another one if it's still not working.

Have a nice day!
